{{- if and .Values.k13d.ai.apiKey (not .Values.k13d.ai.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k13d.fullname" . }}-api-key
  labels:
    {{- include "k13d.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.k13d.ai.existingSecretKey }}: {{ .Values.k13d.ai.apiKey | b64enc | quote }}
{{- end }}
---
{{- if and .Values.k13d.database.password (not .Values.k13d.database.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k13d.fullname" . }}-db
  labels:
    {{- include "k13d.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.k13d.database.existingSecretKey }}: {{ .Values.k13d.database.password | b64enc | quote }}
{{- end }}
